name: Build and Deploy to Firebase

on:
  push:
    branches:
      - main  # Adjust if your main branch has a different name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'latest'

      - name: Install dependencies
        run: flutter pub get

      - name: Build web app
        run: flutter build web

      - name: Deploy to Firebase
        uses: wzieba/Firebase-Action@v2
        with:
          args: deploy --only hosting
        env:
          FIREBASE_AUTH_TOKEN: ${{ secrets.FIREBASE_AUTH_TOKEN }}
